
List meleeWeaponList = [
  "Rustblade",
  "Rotspike",
  "Iron Pipe",
  "Dustdagger",
  "Rodent Claw",
  "Grimclaw",
  "Junkspike",
  "Slagknuckle",
  "Corroblade",
  "Wasteland Whirl",
  "Scrochpike",
  "Gutter Spike",
  "Ashenfang",
  "Shivver",
  "DustDevil",
  "Rubble Raker",
  "Feral Fang",
  "Chaosclaw",
  "Shadow Sjiv",
  "Fallout Fist",
  "Slag Slicer",
  "Ironclad",
  "Acid Edge",
  "Bolted Baton",
  "Gutter Blade",
  "Pipe Dagger",
  "Cog Crusher",
  "Gear Grappler",
  "Corroded Cleaver",
  "Barbed Knuckles",
  "Chain Hook",
  "Rebar Spear",
  "Blade Gauntlet",
  "Razor Chain",
  "Grit Blade",
  "Pipe Cleaver",
];
