
List handgunList = [
  "Ruststormer",
  "Gritfire",
  "Scrapshooter",
  "Slumrunner",
  "Ruinblaster",
  "Junkcaster",
  "Gloomstriker",
  "Wastewarden",
  "Shadowblaze",
  "Grimtrigger",
  "Desolator",
  "Emberthorn",
  "Dustwhisper",
  "Voidpistol",
  "Ashrend",
  "Viperbite",
  "Grimeburner",
  "Corrodbolt",
  "Shradpistol",
  "Flithfinger",
  "Cindercaster",
  "Poxpistol",
  "Shadowscorch",
  "Shrapnel",
  "Ashenstrike",
  "Rustbiter R-9",
  "Anarchy A9",
  "Ghostshot G-22",
  "Sludgefire",
];


List smgList = [
  "Scavenger SMG",
  "Ruinmaker",
  "Wastelander PDW",
  "Chaos Cycler",
  "Ruststinger",
  "Slumshadow",
  "Bladebreaker",
  "Inferno Veiler",
  "Plague Pulse",
  "Grimfire GX-9",
  "Echelon Echo",
  "Abyss Balster",
  "Fallout Fury",
  "Venom Viper",
  "Nomad Nova",
  "Havoc Harvester",
  "Havoc M1",
  "Fury F5",
  "Crimson Serpent",
  "Soulslayer",
  "Specter",
  "Silent Fury",
  "Death's Whisper",
  "Scrapmaster SMG",
  "Biohazard Bralwer",
  "Plague Sprayer",
  "Devil Cycler",
  "Slagstorm",
  "Outland SMG",
  "Scourgehunter",
  "Ebonshard Subrifle",
  "Blightcaster",
];


List assaultRifleList = [
  "Viperstrike X-23",
  "Shadowfire M1K",
  "Venomfang A3",
  "Hydra-7D",
  "Ravage XR-6",
  "Ironsoul I-22",
  "Darkstar D-19",
  "Nemesis Fury-7",
  "Specterburst S-13",
  "Ravage XC-2",
  "Bloodhawk BH-10",
  "Scourgebreaker",
  "Stormshard SS-10",
  "Bloodhawk BH-03",
  "Trinity T-2",
  "Viper-7X",
  "Enforcer MK-II",
  "Ravager-ET",
  "Vortex",
  "Stinger-5R",
  "Sentinel-9S",
  "Tempest-4D",
  "Wraith-8K",
  "Talon-X",
  "Slayer-9",
];


List sniperRifleList = [
  "Ruststalker",
  "Desolation Marksman",
  "Scopecaster",
  "Ruinseeker",
  "Wasteland Whisperer",
  "Dustsniper",
  "Forsaken Lancer",
  "Apocalyptech",
  "Anarchy Hunter",
  "Chaosstalker",
  "Grim Horizon Rifle",
  "Outlandish Sharpshooter",
  "Decayseeker",
  "Echo of Ruin",
  "Rogue Sentinel",
  "Misery's Gaze",
  "Ravagestrike",
  "Chaos Bringer",
  "Hellhound",
  "Hellfire",
  "Nighthawker",
  "Specter-5",
  "Shadowstalker",
  "Wraith-8",
  "Shadowfire",
  "Vorpal Viper",
  "Marauder-X",
  "Widowmaker",
  "Voidstalker",
  "Sorrowseeker",
];


List shotgunList = [
  "Scattergun",
  "Cindershot",
  "Gutter Reaper",
  "Wasteland Widow",
  "Cralwer's Bane",
  "Rusted Mauler",
  "Ashen Hailstorm",
  "Barrel Breaker",
  "Dustroamer",
  "Pipe Marauder",
  "Slum Sweeper",
  "Nomad's Reach",
  "Forsaken Blaster",
  "Debris Dispenser",
  "Soot Stalker",
  "Pit Viper",
  "Brick Breaker",
  "Desolation Deliverer",
  "Gutter Grunt",
  "Ruststorm 12-Gauge",
  "Scrapfire-L",
  "Grim Reaper 10",
  "Grimy Goliath",
  "Boomstick",
  "Annihilator",
  "Outlaw's Bane",
  "Shrapnel Shredder",
  "Chaos Cannon",
  "Dystoblaster",
  "Junkyard Jolt",
  "Apex Agilator",
  "Ruin Reaver",
  "Fallout Frenzy",
  "Viper Vanguard",
  "Harbringer of Havoc",
  "Ravage Roamer",
];